# Generated by Django 2.2.6 on 2020-11-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Member',
        ),
    ]
